"use client";

import { useState } from "react";

export default function AIPurchaseOrderGenerator() {
  const [prompt, setPrompt] = useState("");
  const [result, setResult] = useState("");

  function generatePO() {
    if (!prompt.trim()) return;

    setResult(`
Purchase Order

Supplier: Dell

Description:
50 Dell Latitude Laptops

Estimated Amount:
$75,000

Status:
Draft

Notes:
Generated by AI Procurement Assistant.
    `);
  }

  return (
    <div className="rounded-2xl bg-white p-6 shadow">

      <h2 className="mb-4 text-2xl font-bold">
        🤖 AI Purchase Order Generator
      </h2>

      <textarea
        rows={5}
        value={prompt}
        onChange={(e) => setPrompt(e.target.value)}
        placeholder="Describe the purchase order..."
        className="w-full rounded-xl border p-4"
      />

      <button
        onClick={generatePO}
        className="mt-4 rounded-xl bg-blue-600 px-5 py-3 text-white hover:bg-blue-700"
      >
        Generate Purchase Order
      </button>

      {result && (
        <pre className="mt-6 whitespace-pre-wrap rounded-xl bg-gray-100 p-4">
          {result}
        </pre>
      )}

    </div>
  );
}